### ISSUE TITLE
add readme & brief repo description

### ISSUE THREAD

**Issue by cblgh** [cryptoscope/librarian#2]
hiyo. was just going through repos in anticipation of our call & felt that librarian would benefit from having a concise description of:
* what it is
* why it exists
* what it does
* and optionally: how it connects to the other cryptoscope components

i can try writing the readme after we've talked about it on a call? :)

**Comment by cryptix** [comment]
oi.

As of https://github.com/cryptoscope/margaret/pull/16 this repo is deprecated but I forgot to pull the plug here.

I _think_ I will mark it read-only...?

**Comment by cryptix** [comment]
Done as of 0b961f407d5fde62988fac297c7640fa82b6d7dc
